# Generated by Django 3.2.7 on 2021-09-26 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 10, 5, 35, 93258)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='log_in',
            field=models.TimeField(default=datetime.datetime(2021, 9, 26, 10, 5, 35, 93280)),
        ),
    ]
