# Generated by Django 3.2.7 on 2021-09-26 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210926_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 11, 12, 21, 836803)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='log_in',
            field=models.TimeField(default=datetime.datetime(2021, 9, 26, 11, 12, 21, 836825)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
