# Generated by Django 3.2.7 on 2021-09-26 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210926_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 9, 26, 11, 13, 24, 244356)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='log_in',
            field=models.TimeField(default=datetime.datetime(2021, 9, 26, 11, 13, 24, 244378)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
